### ISSUE TITLE
Erreur lien doc

### ISSUE THREAD

**Issue by Bosquetia** [lunarok/jeedom_telegram#20]
Hello,

En Jeedom v3.1.7, avec la dernière stable du plugin telegram, le ? ne renvoit pas vers la bonne doc.
cf ce post du forum https://www.jeedom.com/forum/viewtopic.php?f=140&t=31145

**Comment by lunarok** [comment]
Fait https://github.com/lunarok/jeedom_telegram/commit/643df68de2da2176aa15ab728bd843619aaa6c4e
