### ISSUE TITLE
Compatibilité disable_notify avec camera?

### ISSUE THREAD

**Issue by fwehrle** [lunarok/jeedom_telegram#21]
Salut Lunarok,

Je cherche à envoyer des notifications silencieuses de camera avec ton plugin telegram.
Mais je ne trouve pas de solution et j'ai l'impression que l'option disable_notify n'est pas passée à télégram quand on utilise la commande "Enregistrer" du plugin camera.
Est-ce que par hasard tu aurais une astuce pour ca?

Merci

**Comment by lunarok** [comment]
voir avec le plugin camera, c'est lui qui appelle les notifications, mais actuellement non il n'y a pas moyen de paramétrer quoi que ce soit avec ce plugin (meme le texte envoyé "Alerte sur ..." n'est pas paramétrable)
à proposer à loic

**Comment by fwehrle** [comment]
Ok. Je vais lui demander.
Pour le texte par contre, ca marche bien : message passe bien l'info à telegram, je m'en sers tout les jours. (je crois que c'est avec les mail qu'on a "alerte..")
Title je ne suis pas sur par contre.. 
Merci
