### ISSUE TITLE
[STABLE : 2018-12-07 03:34:36] Erreur lors de l'envoi telegram : {"ok":false,"error_code":400,"description":"Bad Request: chat_id is empty"}

### ISSUE THREAD

**Issue by skyline-ch** [lunarok/jeedom_telegram#23]
Salut Lunarok,
depuis quelques jour mes jeedom n'envoie plus de message sur telegram, j'ai une erreure : 
`Erreur lors de l'envoi telegram : {"ok":false,"error_code":400,"description":"Bad Request: chat_id is empty"}`

Après avoir chercher dans ton code et ajouter quelques log pour comprendre, il semble y avoir un souci avec la commande : 
`$to[] = $cmd->getConfiguration('chatid');`
et 
`$to[] = $this->getConfiguration('chatid');`

de la fonction "execute" dans le fichier telegram.class.php
En effet dans les logs que j'ai ajouter, je constate que ses commandes ne retourne pas de valeur et donc le paramètre chat_id est vide.

Après avoir forcer la valeur de chat_id pour tester je reçois bien les messages du bot en revanche les interaction me retourne toujours "Message reçu"

**Comment by lunarok** [comment]
les chatid sont récupérés à la création de la cmd, ils ne peuvent pas manquer (c'est leur logicalid, c'est donc lui qui permet de connaitre si il y a un retour pour cette commande dans les interactions)

**Comment by skyline-ch** [comment]
Bien chez moi sur la version stable et Bêta de jeedom, sur 2 machines différente j'ai se même problème, j'ai même créer un nouveau boot pour voir si cela ne venais pas de l'actuelle mais le problème es le même.

J'ai pas eu plus le temps de cherche, comme tu la surement constater actuellement je ne suis plus présent pour des raison personnel et professionnel, donc pas vraiment plus d'infos a te donner que se qui est dans le premier poste si se n'ai que j'ai absolument rien toucher sur mes jeedom depuis plusieurs mois sauf les mises à jours

Comme tu peux le voir sur les capture si dessous que je viens de réaliser j'ai bien la dernière version stable Github et il y as bien se message d'erreur, et rien n'es reçu sur telegram

![capture173](https://user-images.githubusercontent.com/13089438/50737370-9ad08900-11c8-11e9-8fbf-7897b8e52672.png)
![capture174](https://user-images.githubusercontent.com/13089438/50737371-9ad08900-11c8-11e9-898e-2cf2ff5b2cb8.png)

Cordialement

**Comment by lunarok** [comment]
C'est pas le code le pb encore une fois, c'est normal d'utiliser ce paramètre
Le pb c'est que les cmds ne l'aient pas, si tu regardes dans la conf avancée de la cmd user, son logicalid c'est le chatid et en configuration elle a un paramètre chatid
Si c'est pas le cas, c'est la création qui n'est pas bonne, il faut le recréer

Désolé mais je viens de refaire l'essai, une création d'user il y a bien le chatid, donc je clos, je fais pas de support sur github
