### ISSUE TITLE
Rendre le "timeout" d'envoi de message paramétrable

### ISSUE THREAD

**Issue by tpoisson** [lunarok/jeedom_telegram#24]
Bien le bonjour,

Est-il possible de rendre paramétrable le timeout de la requête d'envoi de message ?
Actuellement il est fixé à 30 secondes en dur et je trouve ça un peu long :)

Merci !

Thomas

**Comment by lunarok** [comment]
Non, ca va pas dans le sens de la simplification et accès pour tous, déjà qu'il y a suffisamment d'utilisateurs à avoir du mal avec telegram.
30s c'est pour éviter les pbs de connexion lente et il faudrait ajouter aussi le paramètre de retry.

**Comment by tpoisson** [comment]
Je ne vois pas trop le rapport avec les utilisateurs qui ont du mal avec Telegram.
Il faudrait dans ce cas mettre ce paramètre dans la configuration du plugin en mode "Configuration avancée".

Ce paramètre m'est utile car j'utilise le plug-in Notification Manager, et je n'ai pas envie d'attendre 30 secondes avant d'être notifié si Telegram est non fonctionnel.

**Comment by lunarok** [comment]
Tu n'es pas le seul à l'utiliser avec notification manager ...
Ca n'existe pas le principe de "configuration avancée" depuis plusieurs versions (et il n'y a pas de configuration de plugin sur telegram)
Ton besoin veut dire 2 appels en base inutiles pour le reste des utilisateurs. Entre pénaliser tout le monde (y compris moi) ou mettre en place cette option, désolé

**Comment by tpoisson** [comment]
C'est dommage de ne pas rendre paramétrable toutes les options que peut offrir un plugin.
Je vais continuer à éditer le fichier à chaque mise à jour du plugin.

Pour le coup des 2 appels supplémentaires, tout cela est loin d'être optimal.
