### ISSUE TITLE
Soucis avec l'API KEY

### ISSUE THREAD

**Issue by Blackir62** [lunarok/jeedom_telegram#30]
Bonjour,

En cherchant à lancer des actions via l'API Jeedom avec un script python, je me suis rendu compte que Télégram n'utilise pas la bonne API KEY.
Si je vais dans les options avancées d'une des commandes Télégram, l'URL directe utilise la clé API global de Jeedom et non pas l'API Key local Telegram.
Et si j'apelle l'adresse en y mettant l'API Key local Telegram, j'obtiens une erreur "Vous n'êtes pas autorisé à effectuer cette action 1, IP :  XX.XX.XX.XX"
J'ai vérifié, l'API Key local Telegram est bien activée, je l'ai regénéré et redémarré le plugin en debug, dans les logs on vois bien l'API KEY local apparaitre pourtant.

[2020-05-02 21:38:51][DEBUG] : https://blackir.ddns.net:443/plugins/telegram/core/api/jeeTelegram.php?apikey=956hNn9OlTyviFHMvVhVSuAXdsSfvNrs&id=130
[2020-05-02 21:38:51][DEBUG] : {"ok":true,"result":true,"description":"Webhook was set"}

Mais le résultat reste sans succes.

Merci.

**Comment by lunarok** [comment]
GitHub n'est pas un support, pas d'issue ici juste de la configuration
